spring.application.name=FACTURACION-SERVICE
server.port=${PORT:8083}

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (NEON / POSTGRESQL)
# ===============================

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-restless-paper-aqq08c59-pooler.c-8.us-east-1.aws.neon.tech/neondb?}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=npg_YeZxUW74nzXs
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SHOW_SQL:true}

#Config Eureka
eureka.client.service-url.defaultZone=https://eureka-server-y6q9.onrender.com/eureka/
